CREATE TABLE product_category (
id INT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
description TEXT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
deleted_at TIMESTAMP DEFAULT NULL
);

CREATE TABLE product (
id INT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
description TEXT,
SKU VARCHAR(255) NOT NULL,
category_id INT,
inventory_id INT,
FOREIGN KEY (category_id) REFERENCES product_category(id),
FOREIGN KEY (inventory_id) REFERENCES product_inventory(id),
price DECIMAL(10, 2) NOT NULL,
discount_id INT,
FOREIGN KEY (discount_id) REFERENCES discount(id),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
deleted_at TIMESTAMP DEFAULT NULL
);

CREATE TABLE product_inventory (
id INT PRIMARY KEY,
quantity INT NOT NULL,
product_id INT,
FOREIGN KEY (product_id) REFERENCES product(id),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
deleted_at TIMESTAMP DEFAULT NULL
);

CREATE TABLE discount (
id INT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
description TEXT,
discount_percent DECIMAL(5, 2) NOT NULL,
active BOOLEAN DEFAULT 0,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
deleted_at TIMESTAMP DEFAULT NULL
);
